### PR TITLE
fix log for NodeID(#178)

### LINKED ISSUE #178: can't print NodeID with log
RAFTCPP_LOG(RLL_INFO) << node_id; will be error

### PR DESCRIPTION
**Pull request by xzhangxian1008**
close #178

### CODE REVIEW

File: src/common/id.h [hunk 1]
```diff
@@ -73,6 +74,12 @@ class NodeID : public BaseID {
         return os;
     }
 
+    std::stringstream &operator<<(std::stringstream &ss) {
+        ss << "{\n"
+           << "    nodeId:" << ToHex() << "\n}";
+        return ss;
+    }
+
```
Comment (jovany-wang) [inline src/common/id.h:82]:
```c++
    std::stringstream &operator<<(std::stringstream &ss) {
        ss << "{\n\tnodeId:" << ToHex() << "\n}";
        return ss;
    }
```

**Review by jovany-wang — COMMENTED** [review]
Can you also add a test in logging_test.cc ?

**Comment by xzhangxian1008** [comment]
> Can you also add a test in logging_test.cc ?

I will
